const seedData = [
  {
    id: "seed-1",
    name: "Blue North Face Backpack",
    desc: "Navy blue backpack with a broken left zipper. Has a chemistry textbook and notebook inside.",
    email: "marcus.j@university.edu",
    category: "other",
    location: "Library 2nd Floor",
    date: "Mar 5, 2026",
    status: "lost",
    image: null,
  },
  {
    id: "seed-2",
    name: "iPhone 15 Pro (Space Black)",
    desc: "Black iPhone with a cracked screen protector and a clear case. Lock screen is a golden retriever.",
    email: "sarah.k@university.edu",
    category: "phone",
    location: "Student Union Food Court",
    date: "Mar 7, 2026",
    status: "found",
    image: null,
  },
  {
    id: "seed-3",
    name: "Silver MacBook Air M2",
    desc: "13-inch MacBook Air with stickers on the lid — one says 'Hello World' and another is a Python logo.",
    email: "dev.patel@university.edu",
    category: "laptop",
    location: "Engineering Building Room 204",
    date: "Mar 3, 2026",
    status: "claimed",
    image: null,
  },
  {
    id: "seed-4",
    name: "Car & Dorm Keys on Lanyard",
    desc: "Set of 3 keys on a red university lanyard. Includes a Toyota key fob and two brass keys.",
    email: "jenna.w@university.edu",
    category: "keys",
    location: "Gym Locker Room",
    date: "Mar 8, 2026",
    status: "lost",
    image: null,
  },
  {
    id: "seed-5",
    name: "Sony WH-1000XM5 Headphones",
    desc: "Black over-ear noise-cancelling headphones in a hard carrying case. Name 'Alex' written inside the band.",
    email: "alex.m@university.edu",
    category: "headphones",
    location: "Chemistry Lab 101",
    date: "Mar 6, 2026",
    status: "found",
    image: null,
  },
  {
    id: "seed-6",
    name: "Gray Nike Hoodie (Size L)",
    desc: "Dark gray Nike hoodie with a small bleach stain on the right sleeve. Left in a lecture hall seat.",
    email: "tina.r@university.edu",
    category: "clothing",
    location: "Humanities Hall Room 310",
    date: "Mar 9, 2026",
    status: "lost",
    image: null,
  },
];

export default seedData;
